name: Hello World

on: [push, pull_request]

jobs:
  hello:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Say hello
      run: |
        echo "desde aca manejo el mensaje !! "
        echo "Ejecutándose en: ${{ runner.os }}"
        echo "Repositorio: ${{ github.repository }}"
        echo "Evento: ${{ github.event_name }}"
        echo "Ref: ${{ github.ref }}"
        echo "Actor: ${{ github.actor }}"
        echo "Mensaje personalizado: ¡Hola desde el flujo de trabajo!"
        echo "Mensaje adicional: ¡Este es un mensaje extra!"